### ISSUE TITLE
Update PyPi / Links to sourceforge?

### ISSUE THREAD

**Issue by quietlyconfident** [tomp/python-metar#15]
It's kind of hard to figure out where the home of this code is, because the PyPi page points to SourceForge, which looks long dead.

Likewise the PyPi page doesn't look like its been updated in a long time, version 1.4 was released in 2009.

Unless there is a compelling reason for the current state of play, any objection to some combination of:
- Updating PyPi to point to this Github Repository
- Incrementing the version number and publishing a new build?
- Deleting the SourceForge page, or alternately, updating the documentation there so that its clear the project is actually happening here and providing a link?

**Comment by tomp** [comment]
Erik,

Thanks for contacting me about this.  I agree with your suggestions and
will try to get this cleaned up this weekend.

Tom

**Comment by tomp** [comment]
I've updated the project metadata to point to GitHub as the source repository.  There have been a few minor bug fixes in the docs over the last few months, so I bumped the version to 1.5, as well.
