### ISSUE TITLE
Typo in metar/station.py, line 39

### ISSUE THREAD

**Issue by marjetika** [tomp/python-metar#17]
in file: metar/station.py, line 39:

> print(sta_id, stations[sta_id].name, stations[sat_id].country)

instead of sat_id there should be sta_id

**Comment by marjetika** [comment]
I tried to create a pull request and change the code, but I think I don't have the right permissions. 
#

**Comment by marjetika** [comment]
#16

**Comment by marjetika** [comment]
I tried to create a pull request and change the code, but I think I don't have the right permissions. 
#16

**Comment by marjetika** [comment]
This refers to phobson/python-metar

**Comment by marjetika** [comment]
This was fixed and merged.

**Comment by tomp** [comment]
Ok. FWIW, I don't support phobson's fork.  If that's what you're using, you probably want to file issues on his page.

**Comment by marjetika** [comment]
I posted it here by accident. Sorry. But I couldn't remove it, so I added the other two comments.
